version: '3'
services:
  api:
   container_name: stock_example_api
   build:
    context: ./backend
   image: stock_example_api:latest
   environment:
     PORT: 8000
     HOST: "0.0.0.0"
   ports:
    - "8000:8000"
#   command: ["gunicorn", "-b", "0.0.0.0:5000", "src.app:app"]
   command: ["python", "main.py"]
  front:
    container_name: stock_example_front
    environment:
      VITE_SERVER_ADRESS: "http://0.0.0.0:8000"
    build:
      context: ./fronend
    image: stock_example_front:latest
    ports:
      - "8080:8080"
    command: [ "http-server", "dist"]
